project_id = "yasbrindfmevbxysrgqd"

[functions.blog-subscribe]
verify_jwt = false

[functions.blog-unsubscribe]
verify_jwt = false

[functions.notify-blog-subscribers]
verify_jwt = false

[functions.reset-daily-stats]
verify_jwt = false

[functions.get-database-metrics]
verify_jwt = false

[functions.auto-delete-emails]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.ping-search-engines]
verify_jwt = false

[functions.google-search-console]
verify_jwt = false
