project_id = "ttgltktefeqluafrvpjl"

[functions.send-test-email]
verify_jwt = false

[functions.fetch-imap-emails]
verify_jwt = false

[functions.email-webhook]
verify_jwt = false

[functions.imap-poll-cron]
verify_jwt = false

[functions.auto-delete-emails]
verify_jwt = false

[functions.check-email-config]
verify_jwt = false
